Updated view to validate redirect passed in to login, added test
adam-murray/django-cms pull request #4
Opened 2020-10-12 09:47 UTC by adam-murray

## Description

## Related resources

* #...
* #...

## Checklist

* [ ] I have opened this pull request against ``develop``
* [ ] I have updated the **CHANGELOG.rst**
* [ ] I have added or modified the tests when changing logic

2020-10-13 19:58 UTC, Aiky30 requested changes
We need to test the open redirect here too, we shouldn't be able to add a dodgy url to next.

2020-10-13 19:58 UTC, Aiky30 commented on cms/views.py
> +        redirect_to = urlquote(redirect_to)
We need to test that a request url with `?next=www.somerandomfakeurl.com`. If the redirect tries to go to that url it's bad because it's an open redirect, Naren was working on that, will be worth touching base with him as he probably thinks you've covered this.

2020-10-14 06:52 UTC, adam-murray commented on cms/views.py
> +        redirect_to = urlquote(redirect_to)
That is fine, I worked through one of these with Naren so I will do it now.

2020-10-14 09:14 UTC, adam-murray commented on cms/views.py
> +        redirect_to = urlquote(redirect_to)
This is already being tested. 

https://github.com/django-cms/django-cms/blob/4d75b926fda163e476d3af3a7a534276429d66d6/cms/tests/test_toolbar.py#L206

2020-10-28 13:27 UTC, Aiky30 approved these changes

2020-10-28 14:43 UTC, merged