Verify that XSS vulnerability isn't actually an issue. (opencms-1017/18)
adam-murray/django-cms pull request #5
Opened 2020-10-13 08:47 UTC by adam-murray

## Description

## Related resources

* #...
* #...

## Checklist

* [ ] I have opened this pull request against ``develop``
* [ ] I have updated the **CHANGELOG.rst**
* [ ] I have added or modified the tests when changing logic

2020-10-13 16:18 UTC, NarenderRajuB approved these changes

2020-10-13 19:51 UTC, Aiky30 requested changes
We will need to add a deprecation notice to this test as they are all just about to be deleted for alias. We will potentially leave this test in: https://github.com/django-cms/django-cms/pull/6918

2020-10-28 13:47 UTC, Aiky30 approved these changes

2020-10-28 13:48 UTC, Aiky30 commented
@adam-murray This is ready to merge into your branch: bugfix/security-vulnerabilities

2020-10-28 14:01 UTC, merged